// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftYar.Infrastructure.Persistence.AppDbContext;

#nullable disable

namespace ShiftYar.Infrastructure.Migrations
{
    [DbContext(typeof(ShiftYarDbContext))]
    [Migration("20260804103441_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftYar.Domain.Entities.AddressModel.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.AddressModel.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.DepartmentModel.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNightLover")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.DepartmentModel.DepartmentName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DepartmentNames");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.DepartmentModel.DepartmentSchedulingSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("AllowCurrentMonthScheduling")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowEveningAfterNightShift")
                        .HasColumnType("bit");

                    b.Property<bool?>("AllowMonthlyRescheduleWithAutoDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool?>("EnableNightShiftDistributionBySeniority")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnableNightShiftPreference")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnforceMaxConsecutiveShifts")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnforceMaxShiftsPerDay")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnforceMinRestDays")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnforceMinimumShiftsForRotatingStaff")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnforceNightShiftMonthlyCap")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnforceSpecialtyCapacity")
                        .HasColumnType("bit");

                    b.Property<bool?>("EnforceWeeklyMaxShifts")
                        .HasColumnType("bit");

                    b.Property<double?>("ExtraShiftRotationWeight")
                        .HasColumnType("float");

                    b.Property<double?>("FairShiftCountBalanceWeight")
                        .HasColumnType("float");

                    b.Property<int?>("FairnessLookbackMonths")
                        .HasColumnType("int");

                    b.Property<bool?>("ForbidDuplicateDailyAssignments")
                        .HasColumnType("bit");

                    b.Property<double?>("GenderBalanceWeight")
                        .HasColumnType("float");

                    b.Property<int?>("MaxConsecutiveNightShifts")
                        .HasColumnType("int");

                    b.Property<int?>("MaxConsecutiveShifts")
                        .HasColumnType("int");

                    b.Property<int?>("MaxNightShiftsPerMonth")
                        .HasColumnType("int");

                    b.Property<int?>("MaxShiftsPerDay")
                        .HasColumnType("int");

                    b.Property<int?>("MaxShiftsPerWeek")
                        .HasColumnType("int");

                    b.Property<int?>("MinEveningShiftsForThreeShiftRotation")
                        .HasColumnType("int");

                    b.Property<int?>("MinFirstShiftForTwoShiftRotation")
                        .HasColumnType("int");

                    b.Property<int?>("MinMorningShiftsForThreeShiftRotation")
                        .HasColumnType("int");

                    b.Property<int?>("MinNightShiftsForThreeShiftRotation")
                        .HasColumnType("int");

                    b.Property<int?>("MinRestDaysBetweenShifts")
                        .HasColumnType("int");

                    b.Property<int?>("MinSecondShiftForTwoShiftRotation")
                        .HasColumnType("int");

                    b.Property<double?>("MonthlyNightCapWeight")
                        .HasColumnType("float");

                    b.Property<int?>("NightShiftDistributionType")
                        .HasColumnType("int");

                    b.Property<double?>("NightShiftDistributionWeight")
                        .HasColumnType("float");

                    b.Property<int?>("NightShiftPreferenceType")
                        .HasColumnType("int");

                    b.Property<double?>("NightShiftPreferenceWeight")
                        .HasColumnType("float");

                    b.Property<bool?>("RequireManagerForEveningShift")
                        .HasColumnType("bit");

                    b.Property<bool?>("RequireManagerForNightShift")
                        .HasColumnType("bit");

                    b.Property<double?>("SeniorityDistributionSlope")
                        .HasColumnType("float");

                    b.Property<double?>("ShiftLabelBalanceWeight")
                        .HasColumnType("float");

                    b.Property<double?>("ShiftManagerRequirementWeight")
                        .HasColumnType("float");

                    b.Property<double?>("SpecialtyPreferenceWeight")
                        .HasColumnType("float");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UserPreferredShiftWeight")
                        .HasColumnType("float");

                    b.Property<double?>("UserUnwantedShiftWeight")
                        .HasColumnType("float");

                    b.Property<double?>("WeeklyMaxWeight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentSchedulingSettings");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.HospitalModel.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiamCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.HospitalModel.HospitalPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("HospitalPhoneNumbers");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.PermissionModel.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.RoleModel.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.RolePermissionModel.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.SecurityModel.OtpCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OtpCodes");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.SecurityModel.PasswordResetCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetCodes");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.SecurityModel.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.Settings.AlgorithmSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<double?>("HYB_ComplexityThreshold")
                        .HasColumnType("float");

                    b.Property<int?>("HYB_MaxIterations")
                        .HasColumnType("int");

                    b.Property<int?>("HYB_Strategy")
                        .HasColumnType("int");

                    b.Property<bool?>("ORT_LogSearchProgress")
                        .HasColumnType("bit");

                    b.Property<int?>("ORT_MaxSolutions")
                        .HasColumnType("int");

                    b.Property<int?>("ORT_MaxTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("ORT_NumSearchWorkers")
                        .HasColumnType("int");

                    b.Property<double?>("ORT_RelativeGapLimit")
                        .HasColumnType("float");

                    b.Property<double?>("SA_CoolingRate")
                        .HasColumnType("float");

                    b.Property<double?>("SA_FinalTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("SA_InitialTemperature")
                        .HasColumnType("float");

                    b.Property<int?>("SA_MaxIterations")
                        .HasColumnType("int");

                    b.Property<int?>("SA_MaxIterationsWithoutImprovement")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("AlgorithmSettings");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftDateModel.ShiftDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HolidayEvent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsHoliday")
                        .HasColumnType("bit");

                    b.Property<string>("PersianDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ShiftDates");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftExchangeModel.ShiftExchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OfferingShiftAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("OfferingUserId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestingShiftAssignmentId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestingUserId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OfferingShiftAssignmentId");

                    b.HasIndex("OfferingUserId");

                    b.HasIndex("RequestingShiftAssignmentId");

                    b.HasIndex("RequestingUserId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("ShiftExchanges");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.SchedulingJobRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("JobId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SchedulingJobRecords");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<int?>("Label")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsOnCall")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftDateId")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShiftDateId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.ShiftRequiredSpecialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HolidayOnCallFemaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("HolidayOnCallMaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("HolidayOnCallTottalCount")
                        .HasColumnType("int");

                    b.Property<int?>("HolidayRequiredFemaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("HolidayRequiredMaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("HolidayRequiredTottalCount")
                        .HasColumnType("int");

                    b.Property<int?>("OnCallFemaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("OnCallMaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("OnCallTottalCount")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredFemaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredMaleCount")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredTottalCount")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("ShiftRequiredSpecialties");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialtyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Specialties");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.SpecialtyName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SpecialtyNames");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftRequestModel.ShiftRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequestAction")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RequestType")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftLabel")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("UserId");

                    b.ToTable("ShiftRequests");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.SmsModel.SmsTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TemplateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SmsTemplates");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CanBeShiftManager")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfEmployment")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal?>("HardshipPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IncludedProductivityPlan")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsProjectPersonnel")
                        .HasColumnType("bit");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OvertimeConsent")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonnelCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumberMembership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftSubType")
                        .HasColumnType("int");

                    b.Property<int?>("ShiftType")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<int?>("TwoShiftRotationPattern")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.UserMonthlyNightQuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExactHolidayWeekendNightShiftCount")
                        .HasColumnType("int");

                    b.Property<int?>("ExactNightShiftCount")
                        .HasColumnType("int");

                    b.Property<int>("PersianMonth")
                        .HasColumnType("int");

                    b.Property<int>("PersianYear")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PersianYear", "PersianMonth")
                        .IsUnique();

                    b.ToTable("UserMonthlyNightQuotas");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.UserPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPhoneNumber");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TheUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.AddressModel.City", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.AddressModel.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.DepartmentModel.Department", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.HospitalModel.Hospital", "Hospital")
                        .WithMany("Departments")
                        .HasForeignKey("HospitalId");

                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Hospital");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.DepartmentModel.DepartmentSchedulingSettings", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.DepartmentModel.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.HospitalModel.HospitalPhoneNumber", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.HospitalModel.Hospital", "Hospital")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("HospitalId");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.RolePermissionModel.RolePermission", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.PermissionModel.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");

                    b.HasOne("ShiftYar.Domain.Entities.RoleModel.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.SecurityModel.OtpCode", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.SecurityModel.PasswordResetCode", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.SecurityModel.RefreshToken", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.Settings.AlgorithmSettings", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.DepartmentModel.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftExchangeModel.ShiftExchange", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.ShiftModel.ShiftAssignment", "OfferingShiftAssignment")
                        .WithMany()
                        .HasForeignKey("OfferingShiftAssignmentId");

                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "OfferingUser")
                        .WithMany()
                        .HasForeignKey("OfferingUserId");

                    b.HasOne("ShiftYar.Domain.Entities.ShiftModel.ShiftAssignment", "RequestingShiftAssignment")
                        .WithMany()
                        .HasForeignKey("RequestingShiftAssignmentId");

                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "RequestingUser")
                        .WithMany()
                        .HasForeignKey("RequestingUserId");

                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");

                    b.Navigation("OfferingShiftAssignment");

                    b.Navigation("OfferingUser");

                    b.Navigation("RequestingShiftAssignment");

                    b.Navigation("RequestingUser");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.Shift", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.DepartmentModel.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.ShiftAssignment", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.ShiftDateModel.ShiftDate", "ShiftDate")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftDateId");

                    b.HasOne("ShiftYar.Domain.Entities.ShiftModel.Shift", "Shift")
                        .WithMany()
                        .HasForeignKey("ShiftId");

                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Shift");

                    b.Navigation("ShiftDate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.ShiftRequiredSpecialty", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.ShiftModel.Shift", "Shift")
                        .WithMany("RequiredSpecialties")
                        .HasForeignKey("ShiftId");

                    b.HasOne("ShiftYar.Domain.Entities.ShiftModel.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId");

                    b.Navigation("Shift");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.Specialty", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.DepartmentModel.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftRequestModel.ShiftRequest", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId");

                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Supervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.LoginHistory", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany("LoginHistories")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.User", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.DepartmentModel.Department", "Department")
                        .WithMany("DepartmentUsers")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("ShiftYar.Domain.Entities.ShiftModel.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId");

                    b.Navigation("Department");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.UserMonthlyNightQuota", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany("MonthlyNightQuotas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.UserPhoneNumber", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany("OtherPhoneNumbers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.UserRole", b =>
                {
                    b.HasOne("ShiftYar.Domain.Entities.RoleModel.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("ShiftYar.Domain.Entities.UserModel.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.DepartmentModel.Department", b =>
                {
                    b.Navigation("DepartmentUsers");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.HospitalModel.Hospital", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("PhoneNumbers");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.PermissionModel.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.RoleModel.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftDateModel.ShiftDate", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.ShiftModel.Shift", b =>
                {
                    b.Navigation("RequiredSpecialties");
                });

            modelBuilder.Entity("ShiftYar.Domain.Entities.UserModel.User", b =>
                {
                    b.Navigation("LoginHistories");

                    b.Navigation("MonthlyNightQuotas");

                    b.Navigation("OtherPhoneNumbers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
